In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\sachi\Downloads\online_retail_II.xlsx")

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

(525461, 8)
Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB
None
            Quantity                    InvoiceDate          Price  \
count  525461.000000                         525461  525461.000000
mean       10.337667  2010-06-28 11:37:36.845017856       4.688834
min     -9600.000000            2009-12-01 07:45:00  -53594.360000
25%         1.000000            2010-03-21 12:20:00       1.250000
50%         3.000000            2010-07-06 09:51:00       2.100000
75%        10.000000            2010-10-15 12:45:00       4.210000
max     19152.000000            2010-12-09 20:01:00   25111.090000
std       107.424110                            NaN     146.126914

         Customer ID
count  417534.000000
mean    15360.645478
min     12346.000000
25%     13983.000000
50%     15311.000000
75%     16799.000000
max     18287.000000
std      1680.811316

MISSING VALUE

In [6]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [7]:
df=df.drop_duplicates()

In [8]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

DUPLICATE ROWS

In [10]:
print("Duplicate Row:",df.duplicated().sum())

Duplicate Row: 0

CLEANING

In [12]:
df = df.drop_duplicates()
df = df.dropna(subset=["Customer ID"])
df=df.dropna(subset=["Description"])
df= df[df["Quantity"]>0]
df = df[df["Price"]>0]

NEW COLUMNS

In [14]:
df["Sales"] = df["Quantity"] * df["Price"]
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["MonthName"] = df["InvoiceDate"].dt.month_name()

SAVE CLEANED DATASET

In [16]:
df.to_csv("cleaned_online_retail.csv",index=False)

In [17]:
print(df.columns.tolist())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Sales', 'Year', 'Month', 'MonthName']

KPIs

In [19]:
total_revenue = df["Sales"].sum()
total_orders = df["Invoice"].unique()
total_customers = df["Customer ID"].nunique()
total_products = df["StockCode"].nunique()
print("Total Revenue:",round(total_revenue,2))
print("Total Orders:",total_customers)
print("Total Products:",total_products)

Total Revenue: 8798233.74
Total Orders: 4312
Total Products: 4017

MONTHLY SALES TREND

In [21]:
monthly_sales = df.groupby(["Year","MonthName"])["Sales"].sum().reset_index()
monthly_sales

    Year  MonthName        Sales
0   2009   December   683504.010
1   2010      April   591982.002
2   2010     August   602224.600
3   2010   December   310656.370
4   2010   February   504558.956
5   2010    January   555802.672
6   2010       July   589736.170
7   2010       June   636371.130
8   2010      March   696978.471
9   2010        May   597833.380
10  2010   November  1166460.022
11  2010    October  1033112.010
12  2010  September   829013.951

TOP 10  PRODUCTS

In [23]:
top_products =(
    df.groupby("Description")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print(top_products)

Description
WHITE HANGING HEART T-LIGHT HOLDER     151339.16
REGENCY CAKESTAND 3 TIER               143727.60
Manual                                  98531.99
ASSORTED COLOUR BIRD ORNAMENT           70291.03
JUMBO BAG RED RETROSPOT                 51644.25
POSTAGE                                 48741.08
ROTATING SILVER ANGELS T-LIGHT HLDR     40156.05
PAPER CHAIN KIT 50'S CHRISTMAS          36871.55
PARTY BUNTING                           35017.30
EDWARDIAN PARASOL NATURAL               34044.75
Name: Sales, dtype: float64

TOP 10 Customers

In [25]:
top_customers = (
    df.groupby("Customer ID")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print(top_customers)

Customer ID
18102.0    349164.35
14646.0    248396.50
14156.0    196549.74
14911.0    152121.22
13694.0    131443.19
17511.0     84541.17
15061.0     83284.38
16684.0     80489.21
16754.0     65500.07
17949.0     60117.60
Name: Sales, dtype: float64

COUNTRY WISE SALES

In [27]:
country_sales =(
    df.groupby("Country")["Sales"]
    .sum()
    .sort_values(ascending=False)
)
print(country_sales)

Country
United Kingdom          7381644.433
EIRE                     356041.860
Netherlands              268784.350
Germany                  202025.391
France                   146107.070
Sweden                    53147.990
Denmark                   50906.850
Spain                     47568.650
Switzerland               43921.390
Australia                 31446.800
Channel Islands           24546.320
Belgium                   24537.580
Norway                    23944.180
Portugal                  23843.460
Italy                     15052.730
Greece                    14335.670
Austria                   13414.330
Cyprus                    11347.100
Japan                      9722.020
Finland                    7379.460
United Arab Emirates       7300.410
Unspecified                5946.580
Malta                      5373.500
Lithuania                  4892.680
USA                        4786.470
Singapore                  4037.770
Poland                     3567.800
Israel                     3199.400
Thailand                   3070.540
Iceland                    1323.320
Canada                     1216.660
Korea                      1118.510
RSA                         931.430
Bahrain                     805.970
West Indies                 536.410
Brazil                      268.270
Nigeria                     140.390
Name: Sales, dtype: float64

MOST SOLD PRODUCTS

In [29]:
most_sold = (
    df.groupby("Description")["Quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)
print(most_sold)

Description
WHITE HANGING HEART T-LIGHT HOLDER    56814
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54610
BROCADE RING PURSE                    48166
PACK OF 72 RETRO SPOT CAKE CASES      45129
ASSORTED COLOUR BIRD ORNAMENT         44431
60 TEATIME FAIRY CAKE CASES           35656
PACK OF 60 PINK PAISLEY CAKE CASES    30871
JUMBO BAG RED RETROSPOT               29519
SMALL POPCORN HOLDER                  25703
BLACK AND WHITE PAISLEY FLOWER MUG    25685
Name: Quantity, dtype: int64

AVERAGE ORDER VALUE

In [31]:
average_order_value = (
    df.groupby("Invoice")["Sales"]
               .sum()
               .mean()
)
print("Average Order Value:", round(average_order_value,2))

Average Order Value: 457.93

SALES BY MONTH

In [33]:
sales_month =(
    df.groupby("MonthName")["Sales"]
    .sum()
    .sort_values(ascending=False)
)
print(sales_month)

MonthName
November     1166460.022
October      1033112.010
December      994160.380
September     829013.951
March         696978.471
June          636371.130
August        602224.600
May           597833.380
April         591982.002
July          589736.170
January       555802.672
February      504558.956
Name: Sales, dtype: float64

CANCELLED ORDERS

In [35]:
cancelled = df[df["Invoice"].astype(str).str.startswith("C")]
print("Cancelled Order:",cancelled["Invoice"].nunique())

Cancelled Order: 0

EXPORT SUMMARY

In [37]:
country_sales.to_csv("country_sales.csv")
top_products.to_csv("top_products.csv")
top_customers.to_csv("top_customers.csv")
monthly_sales.to_csv("monthly_sales.csv")

In [38]:
df.to_csv("cleaned_online_retail.csv",index=False)

In [39]:
import pandas as pd

df = pd.read_excel(r"C:\Users\sachi\Downloads\online_retail_II.xlsx")
df.to_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv", index=False)

In [40]:
import pandas as pd

df = pd.read_excel(r"C:\Users\sachi\Downloads\online_retail_II.xlsx")

print(df.shape)

(525461, 8)

In [41]:
import pandas as pd

df = pd.read_excel(r"C:\Users\sachi\Downloads\online_retail_II.xlsx")

print(df.shape)

(525461, 8)

In [42]:
import pandas as pd

df_excel = pd.read_excel(r"C:\Users\sachi\Downloads\online_retail_II.xlsx")
print("Excel:", df_excel.shape)

df_csv = pd.read_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv")
print("CSV:", df_csv.shape)

Excel: (525461, 8)
CSV: (525461, 8)

In [43]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv")
print(df.columns.tolist())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [44]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\sachi\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\sachi\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sachi\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sachi\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [94]:
engine = create_engine(
    "mysql+pymysql://root:sachin@1234localhost/online_retail"
)

In [96]:
engine = create_engine(
    "mysql+pymysql://root:sachin@1234localhost/online_retail"
)

In [92]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv")

engine = create_engine(
    "mysql+pymysql://root:sachin%401234@localhost/online_retail"
)

df.to_sql(
    "retail_sales",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000,
    method="multi"
)

print("Import Successful!")
print(df.shape)

Import Successful!
(525461, 8)

In [98]:
engine = create_engine(
    "mysql+pymysql://root:YOUR_MYSQL_PASSWORD@localhost/online_retail"
)

In [100]:
engine = create_engine(
    "mysql+pymysql://root:YOUR_MYSQL_PASSWORD@localhost/online_retail"
)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv")

engine = create_engine(
    "mysql+pymysql://root:YOUR_MYSQL_PASSWORD@localhost/online_retail"
)

df.to_sql(
    "retail_sales",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000,
    method="multi"
)

print("Import Successful!")
print(df.shape)

Import Successful!
(525461, 8)

In [105]:
import pymysql

try:
    conn = pymysql.connect(
        host="localhost",
        user="root",
        password="YOUR_MYSQL_PASSWORD",
        database="online_retail"
    )

    print("Connected Successfully!")
    conn.close()

except Exception as e:
    print(e)

(1045, "Access denied for user 'root'@'localhost' (using password: YES)")

In [80]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

password = quote_plus("YOUR_MYSQL_PASSWORD")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/online_retail"
)

In [106]:
import pandas as pd

# CSV Load
df = pd.read_csv(r"C:\Users\sachi\Downloads\cleaned_online_retail.csv")

# Data MySQL me insert
df.to_sql(
    name="retail_sales",
    con=engine,
    if_exists="replace",   # Agar table hai to replace kar dega
    index=False,
    chunksize=5000,
    method="multi"
)

print("✅ Import Successful!")
print(df.shape)

✅ Import Successful!
(525461, 8)